--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 9.1.910
--   Created On : Sunday, 29 December, 2013 
--   DBMS       : MySql 
--   -------------------------------------------------- 


SET FOREIGN_KEY_CHECKS=0;


--  Drop Tables, Stored Procedures and Views 

DROP TABLE IF EXISTS Organizations CASCADE;
DROP TABLE IF EXISTS Vehices CASCADE;

--  Create Tables 
CREATE TABLE Organizations
(
	WMI CHAR(3) NOT NULL COMMENT 'World Manufacturer Identifier (WMI)',
	Name CHAR(80) NOT NULL,
	Address CHAR(255) NOT NULL,
	City CHAR(80) NOT NULL,
	State CHAR(2) NOT NULL,
	PostalCode CHAR(9),
	CreationDate DATE NOT NULL,
	PRIMARY KEY (WMI),
	UNIQUE UQ_Organizations_WMI(WMI)

) ;


CREATE TABLE Vehices
(
	ID NUMERIC(10) NOT NULL,
	WMI CHAR(3) NOT NULL,
	VIN CHAR(17) NOT NULL,
	Manufacturer CHAR(80) NOT NULL,
	ModelYear INTEGER NOT NULL,
	VehicleType CHAR(20) NOT NULL,
	ExhaustHC FLOAT(0) NOT NULL,
	NonExhaustHC FLOAT(0) NOT NULL,
	ExhaustCO FLOAT(0) NOT NULL,
	ExhaustNO2 FLOAT(0) NOT NULL,
	CatalyticConverterPic BLOB NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE UQ_Vehices_ID(ID),
	UNIQUE UQ_Vehices_VIN(VIN),
	KEY (WMI)

) ;



SET FOREIGN_KEY_CHECKS=1;


--  Create Foreign Key Constraints 
ALTER TABLE Vehices ADD CONSTRAINT FK_Vehices_Organizations 
	FOREIGN KEY (WMI) REFERENCES Organizations (WMI);
