--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 9.1.910
--  Created On : Monday, 20 January, 2014 
--  DBMS       : MySql 
--  -------------------------------------------------- 

DROP TABLE IF EXISTS Stats CASCADE;
CREATE TABLE Stats
(
	fileName CHAR(25) NOT NULL,
	numberOfPhotos INTEGER,
	emissionsSamples INTEGER,
	sizeOnDiskInBytes INTEGER,
	binaryBytes INTEGER,
	timeToCreateInMilliseconds BIGINT,
	timeToReadInMilliseconds BIGINT,
	UNIQUE UQ_Stats_fileName(fileName)

) ;


